### PR TITLE
Some potential mod shop navigation fixes

### PR DESCRIPTION
**Pull request by MAFINS**
* Possible solution to #424 ?

@itsjustcurtis  please do take a look and test this when possible. I found some of the uses of the selected option numbers instead of the mod/wheel/paint ids passed to the functions already rather confusing and unnecessary.

### CODE REVIEW

**Comment by MAFINS** [comment]
Further changes made to make menu stay in car mod submenu after applying mod. Los Santos Customs does not hop the user back when purchasing or equipping a car mod.

**Comment by itsjustcurtis** [comment]
I can certainly have a look, however I have made some fairly significant changes in my own fork that may conflict with this. Looking at it, my main concern is the removal of the setwheel/setpaint/setmod function. Without those markers the script went haywire and would continuously apply the selected mod after going back. I always thought LSC took you back a menu, its been so long since I used it though! Removing that function would save a _lot_ of headaches in the script.

**Comment by MAFINS** [comment]
@itsjustcurtis  See latest commit to reduce the looped application of the paint/mod/wheel

**Comment by MAFINS** [comment]
@metoxys You may want to check if bfca41c does fix the indicator for the equipped bike rim, etc. that you mentioned in https://github.com/MAFINS/MenyooSP/issues/447#issuecomment-1363837178

**Comment by metoxys** [comment]
@MAFINS lemme know how I can grab a build artifact (or just send me a link to a built version) and I'll test it for you

**Comment by metoxys** [comment]
All good, I found the artifact, I'll test it

**Comment by metoxys** [comment]
Okay, I tested it @MAFINS @itsjustcurtis 

When LSC style is off, it works flawlessly  
When LSC style is on, the bike wheel menus don't seem to do anything as you scroll and press Enter

**Comment by itsjustcurtis** [comment]
Echoing what Metoxys has said, wheels menu is completely un-functional atm. Paints and Mod parts are working as expected. Going to merge changes from my most recent commits into this and add to my own fork

**Comment by itsjustcurtis** [comment]
Very simple fix

`bool allowSettingWheelPreview = GET_VEHICLE_WHEEL_TYPE(vehicle) != wheelType ||
					(wheelType == WheelType::BikeWheels && isBikeBack ? GET_VEHICLE_MOD(vehicle, VehicleMod::BackWheels) != wheelIndex
						: GET_VEHICLE_MOD(vehicle, VehicleMod::FrontWheels) != wheelIndex);`
						
in the second half of the OR comparision, the script should check that the current wheels are NOT the same as the wheelIndex. swapping the two `==` for `!=` fixes this issue.

**Comment by MAFINS** [comment]
@itsjustcurtis There seem to be some build errors in 33447c4 but if it's actually fine (or can become fine), just make a pull request. A that point, I'll add your fork as a remote and merge your changes with some other things, and increment the version number before pushing a release.

**Comment by itsjustcurtis** [comment]
Yeah there's some minor bugs I still need to address, but I had to get to
bed! I'll send a new pull when I'm happy with the build

Kind regards

Curtis Elliott

**Pull request closed without merging**
