### PR TITLE
Further Vehicle functionality changes

### PR DESCRIPTION
**Pull request by itsjustcurtis**
Vehicle spawner now spawns in place when delete old vehicle is checked (some bugs with trailers that need to be addressed)
Vehicle Max upgrade has been replaced with random upgrade (potentially add toggle to switch between, or additional menu option?)
Removed lights toggle in favour of lights control submenu, lights, turn signals and hazard lights.
Changed menyoo customs functionality to closer match LSC functionality i.e. preview mod before selection with toggle for those that prefer the old menu navigation. (This change needs to be applied to wheels and paints.) 
Added Chameleon as a category in paints menu. Currently empty unless mod colours have been added.
Changed algorithm to calculate number of paint ID's available (scroll does not wrap at upper/lower limits and needs investigating)

### CODE REVIEW

**Review by MAFINS — CHANGES_REQUESTED** [review]
I don't understand some of these commits. One is a big change in the modshop file so the diff is all messed up which is understandable. One is empty, one is adding build files which should already have been ignored unless you forcefully added them to the commit, and this natives.h one just changes unnecessary things? Isn't every argument 8 bytes (4 + padding) for natives? I'd love to cherry pick them but if you could revert natives.h and add a removal of the build files in staging and make another commit (and pull request) it would be appreciated!

**Comment by itsjustcurtis** [comment]
Still getting my head round github lol, I'd changed so much from my last upload I ended up just creating a new fork and uploading every file that visual studio had modified since the last time I downloaded it! I'll get those changes made and resubmit

**Comment by itsjustcurtis** [comment]
changes made. I have a feeling the natives.h change was the result of a suggestion given to me as a solution for the crashing when spawning multiple freemode peds in sequence.

**Review by MAFINS — APPROVED** [review]

**Comment by PAMPERS1** [comment]
how download? Dont work fivem build: 2699

**Comment by Gta5KoRn** [comment]
Hello MAFINS, do you here me? NOT POSSIBLE TO DOWNLOAD FROM HERE, LMAO, :D https://ci.appveyor.com/project/MAFINS/menyoosp/build/artifacts

**Pull request merged**
