### PR TITLE
Added Amphibic car mode 

### PR DESCRIPTION
**Pull request by KillerBoy001**
amphibic car doenst let you drive on water but its like a diffrent version of it , but since you just splash on the waves i think it more intuative

### CODE REVIEW

**Comment by KillerBoy001** [comment]
amphibic car doenst let you drive on water but its lets you float and use your car as a boat ( invisible boat is atached etc ) a diffrent version of it , but since you just splash on the waves i think it more intuative

**Comment by captian7** [comment]
What i see is it just puts your player in a seashark and attaches the vehicle correct? pretty cool

**Comment by captian7** [comment]
Noticed it doesnt save attachments from vehicle, could just temp save the vehicle with attachments then load it when back on land.

**Comment by KillerBoy001** [comment]
Indeed it attaches a seashark, that is made invisible as is the player, it then puts a clone in drivers seat of car so you actually see the driver sitting there..

I look into the attachments.

First finishing my water editor project ( set ocean water height and stuff ) i know how to do it since i had it in my old menu...

**Comment by captian7** [comment]
Should be able to use the stock VehSaver_SaveToFile built into menu and just delete file after loading, or keep overwriting it and just name it amphib.xml

**Comment by PodaruDragos** [comment]
@KillerBoy001, @captian7  how are you guys building this ?

i have no experience with c++ and building from vs 2019 fails.

**Pull request closed without merging**
