### PR TITLE
Fix vehicle despawn in 2944 & 3095

### PR DESCRIPTION
**Pull request by katsutosh**
Fixes: https://github.com/MAFINS/MenyooSP/issues/579

### CODE REVIEW

**Comment by Mers228** [comment]
**Please** show the fix for version 3095

**Comment by vbelevcev** [comment]
best

**Comment by Mers228** [comment]
**Thanks** a lot, one of the **best**!

**Comment by Mers228** [comment]
Please tell me how you can fix the error with SHVDN3 support, when starting with Net it crashes with an error, without Net it works fine, can you fix it somehow?

Thank you for your responsiveness!

**Pull request closed without merging**
