### PR TITLE
Neon experimentation

### PR DESCRIPTION
**Pull request by itsjustcurtis**
Mostly experimenting with underglow, adding animations and colour selection options.

### CODE REVIEW

**Comment by metoxys** [comment]
Does this in any way interfere with the LSC neons? I need to be sure that LSC neons can be reproduced _exactly_ as they are in SP/GTAO

**Comment by itsjustcurtis** [comment]
> 

What do you mean interfere? It adds a bunch of functionality thats not possible

**Comment by metoxys** [comment]
> What do you mean interfere? It adds a bunch of functionality thats not normally possible

If I use a completely normal LSC neon, does it behave exactly like it does before this PR or is something changed?  
For example, if this PR changes neons to some spooner object that is just attached to the car, then it means that it has interfered with the existing functionality

**Comment by itsjustcurtis** [comment]
Then no, its all original, just with additional functionality.

**Review by MAFINS — CHANGES_REQUESTED** [review]
Consider rebasing to master and then keeping the new changes so this PR doesn't have 24 (over the last few weeks) commits including ones that have changes that master already has?

Also looking at a couple of the changes, maybe neon stuff should've been in its own file, including all the looped functions and the getters and setters (rly no need to change anything in GTAvehicle). No need to remove code from the neon colour submenu switch case either (adding the new global variable assignment, if it's necessary, after the existing code seems more appropriate). Even in the neon submenu, maybe only use neonstate and g_neon_colour_set if the options them use it are on?

Also the looped methods for the colour changes maybe only need to be run if the respected feature is turned on? Not sure if that works with the intended purposes but maybe.
Also, MenuConfig.cpp ha s about 22 duplicate lines now. I believe only the 2 loop_neon_delays line were meant to be added.

It's also hard to read the changes with a lot of whitespace removed or added randomly in the files, especially Routine.h. Seems there's a whole bunch of code indented now too. The rebase might help with that too. You can try doing it in a new branch to be safe.
Maybe if I find the time and the opportunity I can do it too

**Comment by itsjustcurtis** [comment]
I assumed that the sheer volume of commits might cause an issue, still
learning my way around how github works, not done a rebase before so I'll
see how that goes.

Fully agree with your loop scripts, I used the rgb loop as a baseline to
build from, but I'm certain that I can combine them all into a single
method that only runs when required.

I've honestly forgotten what changes I made to GTAVehicle, I'll look into
that and revert if necessary.

**Comment by itsjustcurtis** [comment]
@MAFINS I tried a rebase, it seems to have just added a shit load more commits... idk if I did it right or if I made it worse lol

**Pull request closed without merging**
