### PR TITLE
2802.0 compatibility update and functionality

### PR DESCRIPTION
**Pull request by itsjustcurtis**
Adding a number of new functions, as well as significant fixes for old ones. Several issues fixed as noted in the commits. Version update to 1.7.3.

### CODE REVIEW

**Review by MAFINS — CHANGES_REQUESTED** [review]
https://github.com/MAFINS/MenyooSP/blob/67b943b9a21d721b5b32d2f970bef1105fa25cdb/Solution/source/Menu/Menu.cpp#L847-L850

This is meant to keep the index of the currently selected item in bounds so it isn't off the screen (and hence is imperative to the functioning of some submenus). The only way it would reset to the first item would be if currentop or printingop becomes 0 or negative.

**Comment by itsjustcurtis** [comment]
Do you know which submenus so I can test properly? This is the only way that I could think to fix the LSC issue. Unless I build a workaround in there to skip it if the sub isn't menyoo customs?

**Comment by itsjustcurtis** [comment]
Some major bugs found in testing. Closing until ready for resubmission

**Comment by alyxandravance** [comment]
Has FiveM compatibility been updated with this as well?

**Comment by TayMcKenzieNZ** [comment]
Here are the new peds:
-------------------------------------

```
a_c_chimp_02
a_c_rabbit_02
a_f_m_genstreet_01
a_m_m_bankrobber_01
csb_chef_03
csb_dax
csb_labrat
csb_luchadora
g_f_m_fooliganz_01
g_m_m_fooliganz_01
g_m_m_friedlandergoons_01
ig_acidlabcook
ig_chef_03
ig_dax
ig_drfriedlander_02
ig_fooliganz_01
ig_fooliganz_02
ig_furry
ig_gunvanseller
ig_hippyleader
ig_labrat
ig_luchadora
ig_nervousron_02
s_m_m_hazmatworker_01
u_m_m_yulemonster
```

**Comment by metoxys** [comment]
@itsjustcurtis if you like, you can build it this ver and upload it for me so I can test it

**Pull request merged**
