### PR TITLE
Cayo Perico Heist Update

### PR DESCRIPTION
**Pull request by Leve1**

### CODE REVIEW

**Review by ToxxicFuse — COMMENTED** [review]
Awesome! 😃 
But it seems like the memory addresses for Swim Speed and Movement Speed hasn't changed so you could also change

`else if (gameVersion <= eGameVersion::VER_1_0_2060_1_NOSTEAM) `
to
`else if (gameVersion <= eGameVersion::VER_1_0_2189_0_NOSTEAM) `

On line 1690, 1709, 1727 and 1746 in GTAmemory.cpp 
_(Talking about the set and get swim speed and movement speed functions)_ 🙂

**Review by ToxxicFuse — APPROVED** [review]

**Comment by davidnorfolk96** [comment]
Has menyoo been updated for this to use the heist update now?

**Comment by cubiform** [comment]
Is there an ETA for support for the DLC vehicles, settings, etc? Menyoo is one of my favourite tools to use in GTA SP, and the ability to spawn in DLC vehicles from the Cayo Perico Heist would be absolute poggers. Thanks for your efforts!

**Comment by Leve1** [comment]
You can just click show all checks and then details. You should then go to artifacts and there's the download for updated menyoo

**Comment by The-UnXplained** [comment]
Can someone update set & get "VehicleBoostState" and "VehicleBoostCharge" in GTAmemory.cpp please..

**Comment by roscoehussein** [comment]
> 
> 
> You can just click show all checks and then details. You should then go to artifacts and there's the download for updated menyoo

I dont see a detail option

**Comment by Leve1** [comment]
> > You can just click show all checks and then details. You should then go to artifacts and there's the download for updated menyoo
> 
> I dont see a detail option

There is the link https://ci.appveyor.com/project/MAFINS/menyoosp/builds/36918326/artifacts

**Comment by The-UnXplained** [comment]
@Leve1 Can you also update set & get "VehicleBoostState" and "VehicleBoostCharge" in GTAmemory.cpp please..

**Review by MAFINS — APPROVED** [review]

**Comment by WildJohnson** [comment]
Hi, why are there no weapons from the update?  Where Perico Pistol,Combat Shotgun,Military Rifle?

**Pull request merged**
