### PR TITLE
Bug fixes and QOL Updates

### PR DESCRIPTION
**Pull request by itsjustcurtis**
Several commits that bring Menyoo up to date with my own modifications following community feedback. LSC Customs style navigation (previews) now working well with paints and wheels as well as all custom parts. Crash when spawning Peds is now fixed.

### CODE REVIEW

**Review by MAFINS — CHANGES_REQUESTED** [review]
I'm a bit confused as to why it works better as one byte rather than 4 with the same value when in the end it's gonna be read as padding+4 bytes IIRC, but this is probably best moved to natives2.h because of this change (although there are some custom changes made in natives.h as well already but it's probably best to have this moved there so the bug doesn't reappear if natives.h is ever 'updated')

**Comment by MAFINS** [comment]
https://github.com/MAFINS/MenyooSP/blob/eca409dabd059c892de3d4fb036c3b5ce56106c8/Solution/source/Submenus/VehicleModShop.cpp#L2650-L2661

Bit confusing. Is MSWheels2 meant for bikes only and MSWheels3 meant for all other vehicles in your setup?
If so, the split can probably be made in the MSWheels submenu itself with the necessary variable assignments done at the start of both 2 and 3 respectively and that way there isn't even a need to change anything in Menu.cpp.
Do correct me if I'm wrong here

**Comment by itsjustcurtis** [comment]
> https://github.com/MAFINS/MenyooSP/blob/2583727939cded5631c8ebcfab3d8ac32469daba/Solution/source/Natives/natives.h#L656
> 
> I'm a bit confused as to why it works better as one byte rather than 4 with the same value when in the end it's gonna be read as padding+4 bytes IIRC, but this is probably best moved to natives2.h because of this change (although there are some custom changes made in natives.h as well already but it's probably best to have this moved there so the bug doesn't reappear if natives.h is ever 'updated')

I'm still working out the full _why_ this works. Looking at the documentation, it looks like an issue of Microsoft vs C and their interpretations of the Bool data types, with the latter not knowing how to deal with BOOL. The crash issue can be turned on and off by changing this value, so I am confident this is the fix.

I am happy to move the new line to natives2.h on the assumption that it over-writes the native found in natives.h

> https://github.com/MAFINS/MenyooSP/blob/eca409dabd059c892de3d4fb036c3b5ce56106c8/Solution/source/Submenus/VehicleModShop.cpp#L2650-L2661
> 
> Bit confusing. Is MSWheels2 meant for bikes only and MSWheels3 meant for all other vehicles in your setup? If so, the split can probably be made in the MSWheels submenu itself with the necessary variable assignments done at the start of both 2 and 3 respectively and that way there isn't even a need to change anything in Menu.cpp. Do correct me if I'm wrong here

Your assumption is correct, my initial attempt at this did exactly what you suggest, and skipped MSWheels2 completely, however there are a number of variables used in MSWheels3 that are defined in MSWheels2 that causes it to break. I _can_ re-write to account for this, but it would likely need a complete rebuild of the 3 MSWheels subroutines to make it work. This is a reliable workaround, though not ideal. 

Let me know what you think, I'll be making any edits I need to this evening.

**Comment by itsjustcurtis** [comment]
Change to the natives.h file has been restored. Let me know if you want me to make the changes to the MSWheels routines before merging

**Comment by MAFINS** [comment]
> Change to the natives.h file has been restored. Let me know if you want me to make the changes to the MSWheels routines before merging

Oh so the practice that's been followed so far is commenting out the definition in natives.h comepletely and copying it over to natives2.h making the necessary changes. And if natives.h is ever 'updated' from an external source, the compiler will call out the duplicates and they can be commented out again (since there are only a few).

**Comment by MAFINS** [comment]
> Your assumption is correct, my initial attempt at this did exactly what you suggest, and skipped MSWheels2 completely, however there are a number of variables used in MSWheels3 that are defined in MSWheels2 that causes it to break. I can re-write to account for this, but it would likely need a complete rebuild of the 3 MSWheels subroutines to make it work. This is a reliable workaround, though not ideal.

I think that having MSWheels3_ do the same assignments and then carry on as usual would be ideal. That means defining the variables again, whether static or local, and having MSWheels_ go to the right place whether bike or otherwise. That way, there's no need for custom code in Menu.cpp to cater for one specific submenu. If someone in the future decides to make mass changes to these submenus again, they would have to edit Menu.cpp and it might create more issues.

**Comment by MAFINS** [comment]
https://github.com/MAFINS/MenyooSP/commit/d70ff00100a80bb14d153be1a55c6aec8a22882a

@itsjustcurtis Do take a look here if this is the desired effect.
It builds but I cannot test it in-game unfortunately.

**Comment by MAFINS** [comment]
https://github.com/MAFINS/MenyooSP/pull/406/commits/d70ff00100a80bb14d153be1a55c6aec8a22882a

@itsjustcurtis Do take a look if this is the desired effect.
It builds but unfortunately I cannot test in-game.

**Comment by itsjustcurtis** [comment]
@MAFINS I have merged your edits into my own now, what we have in this pull request should be working nicely

**Comment by MAFINS** [comment]
@itsjustcurtis Haha doesn't look like you merged it since my commits aren't in there but I guess you copied it over or merged it another way. I know it can be confusing sometimes but if you stash your own extra changes, you can pull someone else's commits and work from there so it all goes in nicely. Either way, seems like you've got it working in-game now so that's superb.

**Review by MAFINS — APPROVED** [review]

**Pull request closed without merging**
